version: "3.8"

networks:
  common:
    driver: bridge

volumes:
  db_volume:
    driver: local
  app_volume:
    driver: local

services:
  app:
    container_name: super_php_app
    build:
      context: .
      dockerfile: php-engine/Dockerfile
    depends_on:
      - postgres-db
    restart: always
    ports:
      - "8085:80"
    volumes:
      - app_volume:/var/www/html
    networks:
      - common
  postgres-db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/
    networks:
      - common
  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - postgres-db
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres-db
    ports:
      - "8080:8080"
    networks:
      - common


